services:
  lexicon-cli:
    restart: always
    image: lexicon-cli:latest
    build:
      context: .
    volumes:
      - ./bin:/lexicon-cli/bin:ro
      - ./lib:/lexicon-cli/lib:ro
      - ./out:/lexicon-cli/out
    env_file:
      - .env
